[package]
name = "example-keep-these-settings"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.7", features = ["full"] }
termion = "1.5"

[lib]
crate-type = ["cdylib", "lib"]
name = "libkeep_these"
path = "src/lib.rs"

[dependencies.pyo3]
version = "0.14"
